/// Represents a supported currency with its ISO-4217 code, name, symbol, and primary country/territory.
class CurrencyInfo {
  const CurrencyInfo({
    required this.code,
    required this.name,
    required this.symbol,
    required this.country,
    this.flag = '',
  });

  /// 3-letter ISO 4217 currency code (e.g. "PKR", "USD", "EUR").
  final String code;

  /// Human-readable currency name (e.g. "Pakistani Rupee", "US Dollar").
  final String name;

  /// Display symbol or prefix (e.g. "Rs ", "$", "€").
  final String symbol;

  /// Primary country or issuing jurisdiction recognized by Pakistan.
  final String country;

  /// Optional country flag emoji.
  final String flag;

  /// Display label formatted for selectors and lists.
  String get displayLabel => flag.isNotEmpty
      ? '$flag $code - $name ($symbol)'
      : '$code - $name ($symbol)';

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is CurrencyInfo &&
          runtimeType == other.runtimeType &&
          code == other.code;

  @override
  int get hashCode => code.hashCode;

  @override
  String toString() => '$code ($name)';
}

/// Comprehensive list of official circulating currencies of sovereign nations recognized by Pakistan.
///
/// Diplomatic Scope Note:
/// Pakistan officially recognizes all UN Member States with the exception of Israel (ILS) and Armenia (AMD).
/// It also recognizes the Republic of Kosovo (EUR) and the State of Palestine (USD/JOD).
/// Accordingly, all circulating national currencies of Pakistan-recognized countries are included,
/// and ILS and AMD are strictly excluded.
const List<CurrencyInfo> supportedCurrencies = [
  // Primary default & high-usage regional/trade currencies
  CurrencyInfo(
    code: 'PKR',
    name: 'Pakistani Rupee',
    symbol: 'Rs ',
    country: 'Pakistan',
    flag: '🇵🇰',
  ),
  CurrencyInfo(
    code: 'USD',
    name: 'US Dollar',
    symbol: r'$',
    country: 'United States',
    flag: '🇺🇸',
  ),
  CurrencyInfo(
    code: 'EUR',
    name: 'Euro',
    symbol: '€',
    country: 'Eurozone',
    flag: '🇪🇺',
  ),
  CurrencyInfo(
    code: 'GBP',
    name: 'British Pound',
    symbol: '£',
    country: 'United Kingdom',
    flag: '🇬🇧',
  ),
  CurrencyInfo(
    code: 'AED',
    name: 'UAE Dirham',
    symbol: 'AED ',
    country: 'United Arab Emirates',
    flag: '🇦🇪',
  ),
  CurrencyInfo(
    code: 'SAR',
    name: 'Saudi Riyal',
    symbol: 'SAR ',
    country: 'Saudi Arabia',
    flag: '🇸🇦',
  ),
  CurrencyInfo(
    code: 'CAD',
    name: 'Canadian Dollar',
    symbol: r'CA$',
    country: 'Canada',
    flag: '🇨🇦',
  ),
  CurrencyInfo(
    code: 'AUD',
    name: 'Australian Dollar',
    symbol: r'A$',
    country: 'Australia',
    flag: '🇦🇺',
  ),
  CurrencyInfo(
    code: 'CNY',
    name: 'Chinese Yuan',
    symbol: '¥',
    country: 'China',
    flag: '🇨🇳',
  ),
  CurrencyInfo(
    code: 'JPY',
    name: 'Japanese Yen',
    symbol: '¥',
    country: 'Japan',
    flag: '🇯🇵',
  ),
  CurrencyInfo(
    code: 'INR',
    name: 'Indian Rupee',
    symbol: '₹',
    country: 'India',
    flag: '🇮🇳',
  ),
  CurrencyInfo(
    code: 'BDT',
    name: 'Bangladeshi Taka',
    symbol: '৳',
    country: 'Bangladesh',
    flag: '🇧🇩',
  ),
  CurrencyInfo(
    code: 'TRY',
    name: 'Turkish Lira',
    symbol: '₺',
    country: 'Turkey',
    flag: '🇹🇷',
  ),
  CurrencyInfo(
    code: 'MYR',
    name: 'Malaysian Ringgit',
    symbol: 'RM ',
    country: 'Malaysia',
    flag: '🇲🇾',
  ),
  CurrencyInfo(
    code: 'SGD',
    name: 'Singapore Dollar',
    symbol: r'S$',
    country: 'Singapore',
    flag: '🇸🇬',
  ),
  CurrencyInfo(
    code: 'QAR',
    name: 'Qatari Riyal',
    symbol: 'QR ',
    country: 'Qatar',
    flag: '🇶🇦',
  ),
  CurrencyInfo(
    code: 'KWD',
    name: 'Kuwaiti Dinar',
    symbol: 'KD ',
    country: 'Kuwait',
    flag: '🇰🇼',
  ),
  CurrencyInfo(
    code: 'OMR',
    name: 'Omani Rial',
    symbol: 'RO ',
    country: 'Oman',
    flag: '🇴🇲',
  ),
  CurrencyInfo(
    code: 'BHD',
    name: 'Bahraini Dinar',
    symbol: 'BD ',
    country: 'Bahrain',
    flag: '🇧🇭',
  ),

  // All other currencies of recognized countries (Alphabetical by code)
  CurrencyInfo(
    code: 'AFN',
    name: 'Afghan Afghani',
    symbol: '؋',
    country: 'Afghanistan',
    flag: '🇦🇫',
  ),
  CurrencyInfo(
    code: 'ALL',
    name: 'Albanian Lek',
    symbol: 'L',
    country: 'Albania',
    flag: '🇦🇱',
  ),
  CurrencyInfo(
    code: 'AOA',
    name: 'Angolan Kwanza',
    symbol: 'Kz',
    country: 'Angola',
    flag: '🇦🇴',
  ),
  CurrencyInfo(
    code: 'ARS',
    name: 'Argentine Peso',
    symbol: r'$',
    country: 'Argentina',
    flag: '🇦🇷',
  ),
  CurrencyInfo(
    code: 'AZN',
    name: 'Azerbaijani Manat',
    symbol: '₼',
    country: 'Azerbaijan',
    flag: '🇦🇿',
  ),
  CurrencyInfo(
    code: 'BAM',
    name: 'Bosnia-Herzegovina Mark',
    symbol: 'KM',
    country: 'Bosnia and Herzegovina',
    flag: '🇧🇦',
  ),
  CurrencyInfo(
    code: 'BBD',
    name: 'Barbadian Dollar',
    symbol: r'Bds$',
    country: 'Barbados',
    flag: '🇧🇧',
  ),
  CurrencyInfo(
    code: 'BGN',
    name: 'Bulgarian Lev',
    symbol: 'лв',
    country: 'Bulgaria',
    flag: '🇧🇬',
  ),
  CurrencyInfo(
    code: 'BIF',
    name: 'Burundian Franc',
    symbol: 'FBu',
    country: 'Burundi',
    flag: '🇧🇮',
  ),
  CurrencyInfo(
    code: 'BND',
    name: 'Brunei Dollar',
    symbol: r'B$',
    country: 'Brunei',
    flag: '🇧🇳',
  ),
  CurrencyInfo(
    code: 'BOB',
    name: 'Bolivian Boliviano',
    symbol: 'Bs.',
    country: 'Bolivia',
    flag: '🇧🇴',
  ),
  CurrencyInfo(
    code: 'BRL',
    name: 'Brazilian Real',
    symbol: r'R$',
    country: 'Brazil',
    flag: '🇧🇷',
  ),
  CurrencyInfo(
    code: 'BSD',
    name: 'Bahamian Dollar',
    symbol: r'B$',
    country: 'Bahamas',
    flag: '🇧🇸',
  ),
  CurrencyInfo(
    code: 'BTN',
    name: 'Bhutanese Ngultrum',
    symbol: 'Nu.',
    country: 'Bhutan',
    flag: '🇧🇹',
  ),
  CurrencyInfo(
    code: 'BWP',
    name: 'Botswana Pula',
    symbol: 'P',
    country: 'Botswana',
    flag: '🇧🇼',
  ),
  CurrencyInfo(
    code: 'BYN',
    name: 'Belarusian Ruble',
    symbol: 'Br',
    country: 'Belarus',
    flag: '🇧🇾',
  ),
  CurrencyInfo(
    code: 'BZD',
    name: 'Belize Dollar',
    symbol: r'BZ$',
    country: 'Belize',
    flag: '🇧🇿',
  ),
  CurrencyInfo(
    code: 'CDF',
    name: 'Congolese Franc',
    symbol: 'FC',
    country: 'Democratic Republic of the Congo',
    flag: '🇨🇩',
  ),
  CurrencyInfo(
    code: 'CHF',
    name: 'Swiss Franc',
    symbol: 'CHF ',
    country: 'Switzerland',
    flag: '🇨🇭',
  ),
  CurrencyInfo(
    code: 'CLP',
    name: 'Chilean Peso',
    symbol: r'$',
    country: 'Chile',
    flag: '🇨🇱',
  ),
  CurrencyInfo(
    code: 'COP',
    name: 'Colombian Peso',
    symbol: r'$',
    country: 'Colombia',
    flag: '🇨🇴',
  ),
  CurrencyInfo(
    code: 'CRC',
    name: 'Costa Rican Colón',
    symbol: '₡',
    country: 'Costa Rica',
    flag: '🇨🇷',
  ),
  CurrencyInfo(
    code: 'CUP',
    name: 'Cuban Peso',
    symbol: r'$',
    country: 'Cuba',
    flag: '🇨🇺',
  ),
  CurrencyInfo(
    code: 'CVE',
    name: 'Cape Verdean Escudo',
    symbol: 'Esc',
    country: 'Cabo Verde',
    flag: '🇨🇻',
  ),
  CurrencyInfo(
    code: 'CZK',
    name: 'Czech Koruna',
    symbol: 'Kč',
    country: 'Czech Republic',
    flag: '🇨🇿',
  ),
  CurrencyInfo(
    code: 'DJF',
    name: 'Djiboutian Franc',
    symbol: 'Fdj',
    country: 'Djibouti',
    flag: '🇩🇯',
  ),
  CurrencyInfo(
    code: 'DKK',
    name: 'Danish Krone',
    symbol: 'kr',
    country: 'Denmark',
    flag: '🇩🇰',
  ),
  CurrencyInfo(
    code: 'DOP',
    name: 'Dominican Peso',
    symbol: r'RD$',
    country: 'Dominican Republic',
    flag: '🇩🇴',
  ),
  CurrencyInfo(
    code: 'DZD',
    name: 'Algerian Dinar',
    symbol: 'DA ',
    country: 'Algeria',
    flag: '🇩🇿',
  ),
  CurrencyInfo(
    code: 'EGP',
    name: 'Egyptian Pound',
    symbol: 'E£ ',
    country: 'Egypt',
    flag: '🇪🇬',
  ),
  CurrencyInfo(
    code: 'ERN',
    name: 'Eritrean Nakfa',
    symbol: 'Nfk',
    country: 'Eritrea',
    flag: '🇪🇷',
  ),
  CurrencyInfo(
    code: 'ETB',
    name: 'Ethiopian Birr',
    symbol: 'Br',
    country: 'Ethiopia',
    flag: '🇪🇹',
  ),
  CurrencyInfo(
    code: 'FJD',
    name: 'Fijian Dollar',
    symbol: r'FJ$',
    country: 'Fiji',
    flag: '🇫🇯',
  ),
  CurrencyInfo(
    code: 'FKP',
    name: 'Falkland Islands Pound',
    symbol: '£',
    country: 'Falkland Islands',
    flag: '🇫🇰',
  ),
  CurrencyInfo(
    code: 'GEL',
    name: 'Georgian Lari',
    symbol: '₾',
    country: 'Georgia',
    flag: '🇬🇪',
  ),
  CurrencyInfo(
    code: 'GHS',
    name: 'Ghanaian Cedi',
    symbol: 'GH₵',
    country: 'Ghana',
    flag: '🇬🇭',
  ),
  CurrencyInfo(
    code: 'GIP',
    name: 'Gibraltar Pound',
    symbol: '£',
    country: 'Gibraltar',
    flag: '🇬🇮',
  ),
  CurrencyInfo(
    code: 'GMD',
    name: 'Gambian Dalasi',
    symbol: 'D',
    country: 'Gambia',
    flag: '🇬🇲',
  ),
  CurrencyInfo(
    code: 'GNF',
    name: 'Guinean Franc',
    symbol: 'FG',
    country: 'Guinea',
    flag: '🇬🇳',
  ),
  CurrencyInfo(
    code: 'GTQ',
    name: 'Guatemalan Quetzal',
    symbol: 'Q',
    country: 'Guatemala',
    flag: '🇬🇹',
  ),
  CurrencyInfo(
    code: 'GYD',
    name: 'Guyanese Dollar',
    symbol: r'G$',
    country: 'Guyana',
    flag: '🇬🇾',
  ),
  CurrencyInfo(
    code: 'HKD',
    name: 'Hong Kong Dollar',
    symbol: r'HK$',
    country: 'Hong Kong',
    flag: '🇭🇰',
  ),
  CurrencyInfo(
    code: 'HNL',
    name: 'Honduran Lempira',
    symbol: 'L',
    country: 'Honduras',
    flag: '🇭🇳',
  ),
  CurrencyInfo(
    code: 'HTG',
    name: 'Haitian Gourde',
    symbol: 'G',
    country: 'Haiti',
    flag: '🇭🇹',
  ),
  CurrencyInfo(
    code: 'HUF',
    name: 'Hungarian Forint',
    symbol: 'Ft',
    country: 'Hungary',
    flag: '🇭🇺',
  ),
  CurrencyInfo(
    code: 'IDR',
    name: 'Indonesian Rupiah',
    symbol: 'Rp ',
    country: 'Indonesia',
    flag: '🇮🇩',
  ),
  CurrencyInfo(
    code: 'IQD',
    name: 'Iraqi Dinar',
    symbol: 'IQD ',
    country: 'Iraq',
    flag: '🇮🇶',
  ),
  CurrencyInfo(
    code: 'IRR',
    name: 'Iranian Rial',
    symbol: '﷼',
    country: 'Iran',
    flag: '🇮🇷',
  ),
  CurrencyInfo(
    code: 'ISK',
    name: 'Icelandic Króna',
    symbol: 'kr',
    country: 'Iceland',
    flag: '🇮🇸',
  ),
  CurrencyInfo(
    code: 'JMD',
    name: 'Jamaican Dollar',
    symbol: r'J$',
    country: 'Jamaica',
    flag: '🇯🇲',
  ),
  CurrencyInfo(
    code: 'JOD',
    name: 'Jordanian Dinar',
    symbol: 'JD ',
    country: 'Jordan / Palestine',
    flag: '🇯🇴',
  ),
  CurrencyInfo(
    code: 'KES',
    name: 'Kenyan Shilling',
    symbol: 'KSh ',
    country: 'Kenya',
    flag: '🇰🇪',
  ),
  CurrencyInfo(
    code: 'KGS',
    name: 'Kyrgyzstani Som',
    symbol: 'с',
    country: 'Kyrgyzstan',
    flag: '🇰🇬',
  ),
  CurrencyInfo(
    code: 'KHR',
    name: 'Cambodian Riel',
    symbol: '៛',
    country: 'Cambodia',
    flag: '🇰🇭',
  ),
  CurrencyInfo(
    code: 'KMF',
    name: 'Comorian Franc',
    symbol: 'CF',
    country: 'Comoros',
    flag: '🇰🇲',
  ),
  CurrencyInfo(
    code: 'KPW',
    name: 'North Korean Won',
    symbol: '₩',
    country: 'North Korea',
    flag: '🇰🇵',
  ),
  CurrencyInfo(
    code: 'KRW',
    name: 'South Korean Won',
    symbol: '₩',
    country: 'South Korea',
    flag: '🇰🇷',
  ),
  CurrencyInfo(
    code: 'KZT',
    name: 'Kazakhstani Tenge',
    symbol: '₸',
    country: 'Kazakhstan',
    flag: '🇰🇿',
  ),
  CurrencyInfo(
    code: 'LAK',
    name: 'Lao Kip',
    symbol: '₭',
    country: 'Laos',
    flag: '🇱🇦',
  ),
  CurrencyInfo(
    code: 'LBP',
    name: 'Lebanese Pound',
    symbol: 'LL ',
    country: 'Lebanon',
    flag: '🇱🇧',
  ),
  CurrencyInfo(
    code: 'LKR',
    name: 'Sri Lankan Rupee',
    symbol: 'Rs ',
    country: 'Sri Lanka',
    flag: '🇱🇰',
  ),
  CurrencyInfo(
    code: 'LRD',
    name: 'Liberian Dollar',
    symbol: r'L$',
    country: 'Liberia',
    flag: '🇱🇷',
  ),
  CurrencyInfo(
    code: 'LSL',
    name: 'Lesotho Loti',
    symbol: 'L',
    country: 'Lesotho',
    flag: '🇱🇸',
  ),
  CurrencyInfo(
    code: 'LYD',
    name: 'Libyan Dinar',
    symbol: 'LD ',
    country: 'Libya',
    flag: '🇱🇾',
  ),
  CurrencyInfo(
    code: 'MAD',
    name: 'Moroccan Dirham',
    symbol: 'DH ',
    country: 'Morocco',
    flag: '🇲🇦',
  ),
  CurrencyInfo(
    code: 'MDL',
    name: 'Moldovan Leu',
    symbol: 'L',
    country: 'Moldova',
    flag: '🇲🇩',
  ),
  CurrencyInfo(
    code: 'MGA',
    name: 'Malagasy Ariary',
    symbol: 'Ar',
    country: 'Madagascar',
    flag: '🇲🇬',
  ),
  CurrencyInfo(
    code: 'MKD',
    name: 'Macedonian Denar',
    symbol: 'ден',
    country: 'North Macedonia',
    flag: '🇲🇰',
  ),
  CurrencyInfo(
    code: 'MMK',
    name: 'Myanmar Kyat',
    symbol: 'K',
    country: 'Myanmar',
    flag: '🇲🇲',
  ),
  CurrencyInfo(
    code: 'MNT',
    name: 'Mongolian Tögrög',
    symbol: '₮',
    country: 'Mongolia',
    flag: '🇲🇳',
  ),
  CurrencyInfo(
    code: 'MOP',
    name: 'Macanese Pataca',
    symbol: r'MOP$',
    country: 'Macau',
    flag: '🇲🇴',
  ),
  CurrencyInfo(
    code: 'MRU',
    name: 'Mauritanian Ouguiya',
    symbol: 'UM',
    country: 'Mauritania',
    flag: '🇲🇷',
  ),
  CurrencyInfo(
    code: 'MUR',
    name: 'Mauritian Rupee',
    symbol: '₨',
    country: 'Mauritius',
    flag: '🇲🇺',
  ),
  CurrencyInfo(
    code: 'MVR',
    name: 'Maldivian Rufiyaa',
    symbol: 'Rf ',
    country: 'Maldives',
    flag: '🇲🇻',
  ),
  CurrencyInfo(
    code: 'MWK',
    name: 'Malawian Kwacha',
    symbol: 'MK',
    country: 'Malawi',
    flag: '🇲🇼',
  ),
  CurrencyInfo(
    code: 'MXN',
    name: 'Mexican Peso',
    symbol: r'Mex$',
    country: 'Mexico',
    flag: '🇲🇽',
  ),
  CurrencyInfo(
    code: 'MZN',
    name: 'Mozambican Metical',
    symbol: 'MT',
    country: 'Mozambique',
    flag: '🇲🇿',
  ),
  CurrencyInfo(
    code: 'NAD',
    name: 'Namibian Dollar',
    symbol: r'N$',
    country: 'Namibia',
    flag: '🇳🇦',
  ),
  CurrencyInfo(
    code: 'NGN',
    name: 'Nigerian Naira',
    symbol: '₦',
    country: 'Nigeria',
    flag: '🇳🇬',
  ),
  CurrencyInfo(
    code: 'NIO',
    name: 'Nicaraguan Córdoba',
    symbol: r'C$',
    country: 'Nicaragua',
    flag: '🇳🇮',
  ),
  CurrencyInfo(
    code: 'NOK',
    name: 'Norwegian Krone',
    symbol: 'kr',
    country: 'Norway',
    flag: '🇳🇴',
  ),
  CurrencyInfo(
    code: 'NPR',
    name: 'Nepalese Rupee',
    symbol: '₨',
    country: 'Nepal',
    flag: '🇳🇵',
  ),
  CurrencyInfo(
    code: 'NZD',
    name: 'New Zealand Dollar',
    symbol: r'NZ$',
    country: 'New Zealand',
    flag: '🇳🇿',
  ),
  CurrencyInfo(
    code: 'PAB',
    name: 'Panamanian Balboa',
    symbol: 'B/.',
    country: 'Panama',
    flag: '🇵🇦',
  ),
  CurrencyInfo(
    code: 'PEN',
    name: 'Peruvian Sol',
    symbol: 'S/',
    country: 'Peru',
    flag: '🇵🇪',
  ),
  CurrencyInfo(
    code: 'PGK',
    name: 'Papua New Guinean Kina',
    symbol: 'K',
    country: 'Papua New Guinea',
    flag: '🇵🇬',
  ),
  CurrencyInfo(
    code: 'PHP',
    name: 'Philippine Peso',
    symbol: '₱',
    country: 'Philippines',
    flag: '🇵🇭',
  ),
  CurrencyInfo(
    code: 'PLN',
    name: 'Polish Złoty',
    symbol: 'zł',
    country: 'Poland',
    flag: '🇵🇱',
  ),
  CurrencyInfo(
    code: 'PYG',
    name: 'Paraguayan Guaraní',
    symbol: '₲',
    country: 'Paraguay',
    flag: '🇵🇾',
  ),
  CurrencyInfo(
    code: 'RON',
    name: 'Romanian Leu',
    symbol: 'lei',
    country: 'Romania',
    flag: '🇷🇴',
  ),
  CurrencyInfo(
    code: 'RSD',
    name: 'Serbian Dinar',
    symbol: 'din',
    country: 'Serbia',
    flag: '🇷🇸',
  ),
  CurrencyInfo(
    code: 'RUB',
    name: 'Russian Ruble',
    symbol: '₽',
    country: 'Russia',
    flag: '🇷🇺',
  ),
  CurrencyInfo(
    code: 'RWF',
    name: 'Rwandan Franc',
    symbol: 'FRw',
    country: 'Rwanda',
    flag: '🇷🇼',
  ),
  CurrencyInfo(
    code: 'SBD',
    name: 'Solomon Islands Dollar',
    symbol: r'SI$',
    country: 'Solomon Islands',
    flag: '🇸🇧',
  ),
  CurrencyInfo(
    code: 'SCR',
    name: 'Seychellois Rupee',
    symbol: 'SR',
    country: 'Seychelles',
    flag: '🇸🇨',
  ),
  CurrencyInfo(
    code: 'SDG',
    name: 'Sudanese Pound',
    symbol: 'SD ',
    country: 'Sudan',
    flag: '🇸🇩',
  ),
  CurrencyInfo(
    code: 'SEK',
    name: 'Swedish Krona',
    symbol: 'kr',
    country: 'Sweden',
    flag: '🇸🇪',
  ),
  CurrencyInfo(
    code: 'SHP',
    name: 'Saint Helena Pound',
    symbol: '£',
    country: 'Saint Helena',
    flag: '🇸🇭',
  ),
  CurrencyInfo(
    code: 'SLE',
    name: 'Sierra Leonean Leone',
    symbol: 'Le',
    country: 'Sierra Leone',
    flag: '🇸🇱',
  ),
  CurrencyInfo(
    code: 'SOS',
    name: 'Somali Shilling',
    symbol: 'Sh ',
    country: 'Somalia',
    flag: '🇸🇴',
  ),
  CurrencyInfo(
    code: 'SRD',
    name: 'Surinamese Dollar',
    symbol: r'$',
    country: 'Suriname',
    flag: '🇸🇷',
  ),
  CurrencyInfo(
    code: 'SSP',
    name: 'South Sudanese Pound',
    symbol: 'SSP ',
    country: 'South Sudan',
    flag: '🇸🇸',
  ),
  CurrencyInfo(
    code: 'STN',
    name: 'São Tomé Dobra',
    symbol: 'Db',
    country: 'São Tomé and Príncipe',
    flag: '🇸🇹',
  ),
  CurrencyInfo(
    code: 'SYP',
    name: 'Syrian Pound',
    symbol: 'LS ',
    country: 'Syria',
    flag: '🇸🇾',
  ),
  CurrencyInfo(
    code: 'SZL',
    name: 'Swazi Lilangeni',
    symbol: 'L',
    country: 'Eswatini',
    flag: '🇸🇿',
  ),
  CurrencyInfo(
    code: 'THB',
    name: 'Thai Baht',
    symbol: '฿',
    country: 'Thailand',
    flag: '🇹🇭',
  ),
  CurrencyInfo(
    code: 'TJS',
    name: 'Tajikistani Somoni',
    symbol: 'SM',
    country: 'Tajikistan',
    flag: '🇹🇯',
  ),
  CurrencyInfo(
    code: 'TMT',
    name: 'Turkmenistani Manat',
    symbol: 'T',
    country: 'Turkmenistan',
    flag: '🇹🇲',
  ),
  CurrencyInfo(
    code: 'TND',
    name: 'Tunisian Dinar',
    symbol: 'DT',
    country: 'Tunisia',
    flag: '🇹🇳',
  ),
  CurrencyInfo(
    code: 'TOP',
    name: 'Tongan Paʻanga',
    symbol: r'T$',
    country: 'Tonga',
    flag: '🇹🇴',
  ),
  CurrencyInfo(
    code: 'TTD',
    name: 'Trinidad and Tobago Dollar',
    symbol: r'TT$',
    country: 'Trinidad and Tobago',
    flag: '🇹🇹',
  ),
  CurrencyInfo(
    code: 'TZS',
    name: 'Tanzanian Shilling',
    symbol: 'TSh ',
    country: 'Tanzania',
    flag: '🇹🇿',
  ),
  CurrencyInfo(
    code: 'UAH',
    name: 'Ukrainian Hryvnia',
    symbol: '₴',
    country: 'Ukraine',
    flag: '🇺🇦',
  ),
  CurrencyInfo(
    code: 'UGX',
    name: 'Ugandan Shilling',
    symbol: 'USh ',
    country: 'Uganda',
    flag: '🇺🇬',
  ),
  CurrencyInfo(
    code: 'UYU',
    name: 'Uruguayan Peso',
    symbol: r'$U',
    country: 'Uruguay',
    flag: '🇺🇾',
  ),
  CurrencyInfo(
    code: 'UZS',
    name: 'Uzbekistani Som',
    symbol: "so'm",
    country: 'Uzbekistan',
    flag: '🇺🇿',
  ),
  CurrencyInfo(
    code: 'VES',
    name: 'Venezuelan Bolívar',
    symbol: 'Bs.S',
    country: 'Venezuela',
    flag: '🇻🇪',
  ),
  CurrencyInfo(
    code: 'VND',
    name: 'Vietnamese Đồng',
    symbol: '₫',
    country: 'Vietnam',
    flag: '🇻🇳',
  ),
  CurrencyInfo(
    code: 'VUV',
    name: 'Vanuatu Vatu',
    symbol: 'VT',
    country: 'Vanuatu',
    flag: '🇻🇺',
  ),
  CurrencyInfo(
    code: 'WST',
    name: 'Samoan Tālā',
    symbol: r'WS$',
    country: 'Samoa',
    flag: '🇼🇸',
  ),
  CurrencyInfo(
    code: 'XAF',
    name: 'Central African CFA Franc',
    symbol: 'FCFA ',
    country: 'Central African Region',
    flag: '🇨🇲',
  ),
  CurrencyInfo(
    code: 'XCD',
    name: 'East Caribbean Dollar',
    symbol: r'EC$',
    country: 'East Caribbean States',
    flag: '🇦🇬',
  ),
  CurrencyInfo(
    code: 'XOF',
    name: 'West African CFA Franc',
    symbol: 'CFA ',
    country: 'West African Region',
    flag: '🇸🇳',
  ),
  CurrencyInfo(
    code: 'YER',
    name: 'Yemeni Rial',
    symbol: 'YR ',
    country: 'Yemen',
    flag: '🇾🇪',
  ),
  CurrencyInfo(
    code: 'ZAR',
    name: 'South African Rand',
    symbol: 'R ',
    country: 'South Africa',
    flag: '🇿🇦',
  ),
  CurrencyInfo(
    code: 'ZMW',
    name: 'Zambian Kwacha',
    symbol: 'ZK',
    country: 'Zambia',
    flag: '🇿🇲',
  ),
  CurrencyInfo(
    code: 'ZWG',
    name: 'Zimbabwe Gold',
    symbol: 'ZiG ',
    country: 'Zimbabwe',
    flag: '🇿🇼',
  ),
];

/// Immutable lookup map from currency code to CurrencyInfo.
final Map<String, CurrencyInfo> _currencyCodeMap = {
  for (final currency in supportedCurrencies)
    currency.code.toUpperCase(): currency,
};

/// List of all supported 3-letter ISO-4217 currency codes.
final List<String> supportedCurrencyCodes =
    supportedCurrencies.map((c) => c.code).toList(growable: false);

/// Backwards-compatible alias for default currency codes.
const List<String> defaultCurrencyCodes = [
  'PKR',
  'USD',
  'EUR',
  'GBP',
  'AED',
  'SAR',
  'CAD',
  'AUD',
  'CNY',
  'JPY',
  'INR',
  'BDT',
  'TRY',
  'MYR',
  'SGD',
  'QAR',
  'KWD',
  'OMR',
  'BHD',
  'AFN',
  'ALL',
  'AOA',
  'ARS',
  'AZN',
  'BAM',
  'BBD',
  'BGN',
  'BIF',
  'BND',
  'BOB',
  'BRL',
  'BSD',
  'BTN',
  'BWP',
  'BYN',
  'BZD',
  'CDF',
  'CHF',
  'CLP',
  'COP',
  'CRC',
  'CUP',
  'CVE',
  'CZK',
  'DJF',
  'DKK',
  'DOP',
  'DZD',
  'EGP',
  'ERN',
  'ETB',
  'FJD',
  'FKP',
  'GEL',
  'GHS',
  'GIP',
  'GMD',
  'GNF',
  'GTQ',
  'GYD',
  'HKD',
  'HNL',
  'HTG',
  'HUF',
  'IDR',
  'IQD',
  'IRR',
  'ISK',
  'JMD',
  'JOD',
  'KES',
  'KGS',
  'KHR',
  'KMF',
  'KPW',
  'KRW',
  'KZT',
  'LAK',
  'LBP',
  'LKR',
  'LRD',
  'LSL',
  'LYD',
  'MAD',
  'MDL',
  'MGA',
  'MKD',
  'MMK',
  'MNT',
  'MOP',
  'MRU',
  'MUR',
  'MVR',
  'MWK',
  'MXN',
  'MZN',
  'NAD',
  'NGN',
  'NIO',
  'NOK',
  'NPR',
  'NZD',
  'PAB',
  'PEN',
  'PGK',
  'PHP',
  'PLN',
  'PYG',
  'RON',
  'RSD',
  'RUB',
  'RWF',
  'SBD',
  'SCR',
  'SDG',
  'SEK',
  'SHP',
  'SLE',
  'SOS',
  'SRD',
  'SSP',
  'STN',
  'SYP',
  'SZL',
  'THB',
  'TJS',
  'TMT',
  'TND',
  'TOP',
  'TTD',
  'TZS',
  'UAH',
  'UGX',
  'UYU',
  'UZS',
  'VES',
  'VND',
  'VUV',
  'WST',
  'XAF',
  'XCD',
  'XOF',
  'YER',
  'ZAR',
  'ZMW',
  'ZWG',
];

/// Returns the CurrencyInfo for a given currency code, or null if unsupported.
CurrencyInfo? findCurrency(String? code) {
  if (code == null || code.isEmpty) return null;
  return _currencyCodeMap[code.toUpperCase()];
}

/// Checks whether a currency code belongs to a recognized country supported by WalletMelt.
bool isCurrencySupported(String? code) {
  if (code == null || code.isEmpty) return false;
  return _currencyCodeMap.containsKey(code.toUpperCase());
}

/// Returns the display symbol for a given currency code.
String currencySymbolFor(String currency) {
  final info = findCurrency(currency);
  if (info != null) {
    return info.symbol;
  }
  return '$currency ';
}
